### ISSUE TITLE
utils.h doesn't exist, but util.h does

### ISSUE THREAD

**Issue by eddiem3** [arrayfire/arrayfire-fortran#4]
Hi!

Am I using the appropriate version of arrayfire to get this fortran binding running? The compiler kept giving an error that af/utils.h didn't exist. I checked my installation and found that I have af/util.h (not plural). I changed the include file path in fortran_wrapper.cpp to util.h and now I'm not getting that error, but others.

**Comment by pavanky** [comment]
This is from using an older version of arrayfire. Please use latest arrayfire and the master branch of the fortran wrapper.
