### ISSUE TITLE
file extentions for free-form fortran code

### ISSUE THREAD

**Issue by physkets** [arrayfire/arrayfire-fortran#5]
The convention followed for free-form fortran code files, is to use '.f90'. Then it implies compatibility with all further standards. Using .f95, .f03 etc. may lead some compilers to assume fixed-form code.

Ref: http://fortranwiki.org/fortran/show/File+extensions

p.s.  Also, arrays are now written as [1, 2, 3, ... ]
Ref: http://www.fortran90.org/src/best-practices.html#arrays

**Comment by pavanky** [comment]
I could have sworn I fixed the free-form when I updated the repo a few months ago.. 
Looks like I missed that part somehow.

Thanks for pointing out the issues, I'll go ahead and make the changes!  

P.S. All of us at arrayfire are novices when it comes to FORTRAN. I'd appreciate any other feedback you can send our way! Patches would be even better :D

**Comment by pavanky** [comment]
This is fixed in the master branch.
